### ISSUE TITLE
Folder missing on pip install python-docx

### ISSUE THREAD

**Issue by edivaldodelgado** [python-openxml/python-docx#594]
Hi, I'm not sure if this is the right place for posting this but, I've installed the package using pip install python-docx, and tried to execute the first tutorial. Then got this error:

`"Package not found at '%s'" % pkg_file
docx.opc.exceptions.PackageNotFoundError: Package not found at '/home/----/anaconda3/envs/myenv/lib/python3.6/site-packages/docx/templates/default-docx-template'`

Then I went to the folder and there is no _default-docx-template_ folder. I checked here on GitHub and it's there.

**Comment by scanny** [comment]
Hmm, could be a problem with the MANIFEST.ini, that directory was just added on the last release which makes me suspect. I'll check it out here ...

**Comment by scanny** [comment]
Ah, yes, good catch, it looks like there was a "*" in there where it shouldn't have been. I'll push a new release right away. Thanks for reporting this :)

**Comment by scanny** [comment]
Okay, should be fixed now with v0.8.9 available from PyPI. Thanks again for reporting. Please let me know how you go :)

**Comment by scanny** [comment]
Hi @edivaldodelgado, apologies, I should have tested more thoroughly, the problem ran a little deeper than I thought, but works for me now on 0.8.10. I had to install with `pip install python-docx==0.8.10` to get it to pick up from PyPI, but that was probably because I had uploaded it minutes before and I suppose `pip` caches or something. Let me know if it works for you.

**Comment by RogueRaider** [comment]
Hi @scanny 
I am still getting the same symptoms with my 0.8.10 install
` error: can't copy 'docx/templates/default-docx-template': doesn't exist or not a regular file
`
I even tried downloading the source 0.8.10 tarball and running
`python3 setup.py install`
Still got the same result.
The docx/templates/default-docx-template does exist, but it is a folder.

Let me know if you would like any further troubleshooting carried out.

**Comment by scanny** [comment]
@RogueRaider your error is actually different from the original and I am unable to reproduce it. Please post the entire error message.

**Comment by scanny** [comment]
@RogueRaider Ok, I can't reproduce this with either of your commands. In any case, it shouldn't be this hard. Just use `pip install python-docx` and if that doesn't work let me know how it fails. There should be no reason I know of you have to add the `python3 -m pip` bit on the front (although I learn new things every day). Also make sure you have an up-to-date version of pip installed. Also make sure you've completely deleted the extracted tarballs so you're not inadvertently running something old. My trials did not attempt to copy/install default-docx-template, which makes me think maybe your extracts are mixed in with old versions or something. Wipe clean and try again directly with pip.

**Comment by K4zuki** [comment]
@RogueRaider Could you please provide `setuptools` version?

I was facing similar situation. 

#### *Failing* on following setup

- OS: Ubuntu 16.04
- Python: 2.7.10 and 3.5.2
- setuptools: **20.7.0**

#### It *worked* on following setup

- OS: MacOS
- Python: 3.6.5
- setuptools: **40.6.2**

On ubuntu by updating setuptools `pip install -U setuptools` it worked.

**Comment by K4zuki** [comment]
@scanny 
I have no idea about relationship between `setuptools` and this package but it may better to limit its version.

**Comment by RogueRaider** [comment]
@K4zuki 
Thank you for this input. Updating setuptools fixed my issue.
I was trying to install this on ubuntu 16.04. After having some issues with updating pip, I tried a fresh linux install of mint. Still the same problem. Then I tried installing on Windows and python-docx worked with no problems.

So I knew it was something to do with linux and possibly my local config. But following your suggestion I was able to successfully install the package :)

@scanny 
Thanks for your help. Appreciate your time and efforts :)

**Comment by K4zuki** [comment]
@RogueRaider Grad to hear it worked for you 👍

**Comment by titilambert** [comment]
Hello,
I have the same issue with  version 0.8.9.
I don't have the issue with version 0.8.7.
I guess this commit https://github.com/python-openxml/python-docx/commit/ada86c3880f1b070ad6525201610866af4945865 broke the thing.

**Comment by scanny** [comment]
@titilambert Use versoin 0.8.10 and make sure your setuptools is up-to-date (v40.x or so).

**Comment by coder0028** [comment]
@scanny python-docx==0.8.10 installation has missing default-docx-template directory. Is it intentional ?

**Comment by JingyuanHu** [comment]
I met the same problem when install  python-docx==0.8.10. My environment is 
+ setuptools: 50.3.2
+ ubuntu: 16.04
+ python: 3.6.8
+ pip3: 20.2.4

but it works when install python-docx 0.8.7.
Just report

**Comment by teake** [comment]
This issue has been fixed with da75fcf01f7f322e846e2ac3e1936aedd766acc8 as far as I can tell, but somehow that hasn't made it way to the PyPI tarball. The PyPI tarball [python-docx-0.8.10.tar.gz](https://files.pythonhosted.org/packages/e4/83/c66a1934ed5ed8ab1dbb9931f1779079f8bca0f6bbc5793c06c4b5e7d671/python-docx-0.8.10.tar.gz) still has

```
PACKAGE_DATA = {'docx': ['templates/*']}
```

instead of 

```
PACKAGE_DATA = {'docx': ['templates/*.xml', 'templates/*.docx']}
```

So my guess a stale version of the package has been uploaded to PyPI (since the [v0.8.10 tag](https://github.com/python-openxml/python-docx/releases/tag/v0.8.10) references da75fcf01f7f322e846e2ac3e1936aedd766acc8). @scanny could you release a new build of 0.8.10 to PyPI? Perhaps with a wheel as well?

**Comment by scanny** [comment]
Closing as resolved.
